### ISSUE TITLE
Unable to import bricklink_api

### ISSUE THREAD

**Issue by agornost** [BrickBytes/bricklink_api#4]
Hi,

Thanks for the api - worked great until I updated conda, I guess.
Apologies for ignorance, I suspect there is an issue with envvars but here is the trace back that I am getting now:
`>>> import bricklink_api

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Gara/opt/miniconda3/envs/myenv/lib/python3.10/site-packages/bricklink_api/__init__.py", line 3, in <module>
    from . import order
  File "/Users/Gara/opt/miniconda3/envs/myenv/lib/python3.10/site-packages/bricklink_api/order.py", line 4, in <module>
    from .method import method as _method
  File "/Users/Gara/opt/miniconda3/envs/myenv/lib/python3.10/site-packages/bricklink_api/method.py", line 5, in <module>
    from . import auth as _auth
  File "/Users/Gara/opt/miniconda3/envs/myenv/lib/python3.10/site-packages/bricklink_api/auth.py", line 4, in <module>
    import requests_oauthlib as _requests_oauthlib
  File "/Users/Gara/opt/miniconda3/envs/myenv/lib/python3.10/site-packages/requests_oauthlib/__init__.py", line 3, in <module>
    from .oauth1_auth import OAuth1
  File "/Users/Gara/opt/miniconda3/envs/myenv/lib/python3.10/site-packages/requests_oauthlib/oauth1_auth.py", line 9, in <module>
    from requests.compat import is_py3
  File "/Users/Gara/opt/miniconda3/envs/myenv/lib/python3.10/site-packages/requests/__init__.py", line 134, in <module>
    from . import packages
  File "/Users/Gara/opt/miniconda3/envs/myenv/lib/python3.10/site-packages/requests/packages.py", line 15, in <module>
    locals()[package] = __import__(package)
ModuleNotFoundError: No module named 'idna'`

Trying to install idna but it appears to be installed already:
`(myenv) MacBook-Air:bricklink Gara$ pip install idna

Requirement already satisfied: idna in /Users/Gara/opt/miniconda3/envs/myenv/lib/python3.10/site-packages (3.3)`

Any help would be much appreciated.
Thanks

**Comment by agornost** [comment]
God, should have googled a little more - fixed it with `pip install -I --user idna`
